version: 2.1
parameters:
  node-version:
    type: string
    default: "20.10"



commands:
  checkout_yarn_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run: yarn install

# Re-usable job bases
job_default: &job_default
  docker:
    - image: cimg/node:<< pipeline.parameters.node-version >>



jobs:
  yarn:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - node_modules
  build:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - run: yarn build
  lint:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - run: yarn lint
  docker_build_and_test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build -t dblworks/pdf-renderer .
      - run:
          name: Run docker image and check the app is running
          command: |
            docker run --name pdf-renderer -d -p 5017:5017 dblworks/pdf-renderer
            # @TODO(lud, 2023-11-28): figure out how to launch & ping the app on CircleCI
            # sleep 10
            # curl --retry 3 --retry-connrefused http://localhost:5017/livez
            # curl --retry 3 --retry-connrefused http://localhost:5017/readyz
            # curl --retry 3 --retry-connrefused -X POST -d "<html><p>Hello World</p></html>" http://localhost:5017


workflows:
  default:
    jobs:
      - yarn
      - build:
          requires:
            - yarn
      - lint:
          requires:
            - yarn
      - docker_build_and_test:
          requires:
            - build
            - lint
