version: 2.1
parameters:
  node-version:
    type: string
    default: "14.17"

orbs:
  aws-cli: circleci/aws-cli@2.0.0
  aws-ecr: circleci/aws-ecr@7.0.0

# Majority of our jobs require the same setup
# https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
commands:
  checkout_yarn_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run: yarn install

# Re-usable job bases
job_default: &job_default
  docker:
    - image: cimg/node:<< pipeline.parameters.node-version >>



jobs:
  yarn:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - node_modules
  build:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - run: yarn build
  lint:
    <<: *job_default
    steps:
      - checkout_yarn_install
      - run: yarn lint
  docker:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    environment:
      AWS_ACCOUNT_ID: "272343518667"
      AWS_REGION: "eu-central-1"
      AWS_ECR_ACCOUNT_URL: "272343518667.dkr.ecr.eu-central-1.amazonaws.com"
    steps:
      - checkout
      - aws-cli/install
      - aws-ecr/build-image:
          repo: pdf-render
          tag: commit-${CIRCLE_SHA1}
          extra-build-args: '--build-arg="GIT_SHA=${CIRCLE_SHA1}"'



workflows:
  version: 2
  default:
    jobs:
      - yarn
      - build:
          requires:
            - yarn
      - lint:
          requires:
            - yarn
      - docker
